spring:
  # 静态web资源处理配置
  web:
    resources:
      # 默认启用静态资源处理
      add-mappings: true
      cache:
        cachecontrol:
          #缓存时间，s为单位
          max-age: 3600
      chain:
        #资源链自动缓存，默认启用
        cache: true
        #启用资源链：默认禁用
        enabled: true
        #启用压缩资源(gzip, brotli)解析，默认禁用
        compressed: true
  # thymelaef配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&Timezone=Asia/Shanghai
    username: camille
    password: z137946a
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30s
      connection-timeout: 30000
      # 心跳机制（测试连接是否可用）
      connection-test-query: SELECT 1

  redis:
    host: 121.196.30.95
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 200
        min-idle: 5

    password: z137946a

  rabbitmq:
    host: 121.196.30.95
    username: camille
    password: z137946a
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1



mybatis-plus:
  # 配置Mapper.xml映射文件位置
  mapper-locations: classpath:/com/camille/seckill/mapper/xml/*Mapper.xml

logging:
  level:
    com.camille.seckill.mapper: debug
server:
  port: 8080
  address: 0.0.0.0

